openapi: 3.0.0
info:
  title: Sistema de Gerenciamento de Finanças API
    description: API para testar operações CRUD básicas
  version: 1.0.0

servers:
  - url: http://localhost/
    description: Servidor local

tags:
  - name: transacoes
    description: Operações de CRUD para transações
  - name: categorias
    description: Operações de CRUD para categorias

paths:
  /transacoes:
    get:
      tags:
        - transacoes
      summary: Listar todas as transações
      responses:
        '200':
          description: Lista de transações
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transacao'
    post:
      tags:
        - transacoes
      summary: Criar uma nova transação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoInput'
      responses:
        '201':
          description: Transação criada

  /transacoes/{id}:
    get:
      tags:
        - transacoes
      summary: Obter detalhes de uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da transação
    put:
      tags:
        - transacoes
      summary: Atualizar uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoInput'
      responses:
        '200':
          description: Transação atualizada
    delete:
      tags:
        - transacoes
      summary: Remover uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      responses:
        '204':
          description: Transação removida

  /categorias:
    get:
      tags:
        - categorias
      summary: Listar todas as categorias
      responses:
        '200':
          description: Lista de categorias
    post:
      tags:
        - categorias
      summary: Criar uma nova categoria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '201':
          description: Categoria criada

  /categorias/{id}:
    get:
      tags:
        - categorias
      summary: Obter detalhes de uma categoria
      parameters:
        - name: id
          in: path
          required: true
          description: ID da categoria
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da categoria
    put:
      tags:
        - categorias
      summary: Atualizar uma categoria
      parameters:
        - name: id
          in: path
          required: true
          description: ID da categoria
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '200':
          description: Categoria atualizada
    delete:
      tags:
        - categorias
      summary: Remover uma categoria
      parameters:
        - name: id
          in: path
          required: true
          description: ID da categoria
          schema:
            type: integer
      responses:
        '204':
          description: Categoria removida

components:
  schemas:
    Transacao:
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
        valor:
          type: number
        data:
          type: string
          format: date
        tipo:
          type: string
          enum: [receita, despesa]
        categoria_id:
          type: integer
    
    TransacaoInput:
      type: object
      properties:
        descricao:
          type: string
        valor:
          type: number
        data:
          type: string
          format: date
        tipo:
          type: string
          enum: [receita, despesa]
        categoria_id:
          type: integer
      required:
        - descricao
        - valor
        - data
        - tipo
        - categoria_id
    
    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        tipo:
          type: string
          enum: [receita, despesa]
    
    CategoriaInput:
      type: object
      properties:
        nome:
          type: string
        tipo:
          type: string
          enum: [receita, despesa]
      required:
        - nome
        - tipo