openapi: 3.0.0
info:
  title: Sistema de Gerenciamento de Finanças API
  description: API para testar operações CRUD básicas
  version: 1.0.0

servers:
  - url: http://localhost/
    description: Servidor local

tags:
  - name: transacoes
    description: Operações de CRUD para transações
  - name: categorias
    description: Operações de CRUD para categorias

paths:
  /api/financeiro/transacao/listar/todos:
    get:
      tags:
        - transacoes
      summary: Listar todas as transações
      responses:
        '200':
          description: Lista de transações
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transacao'

  /api/financeiro/transacao/cadastrar:
    post:
      tags:
        - transacoes
      summary: Criar uma nova transação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoInput'
      responses:
        '201':
          description: Transação criada

  /api/financeiro/transacao/listar/{id}:
    get:
      tags:
        - transacoes
      summary: Obter detalhes de uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da transação

  /api/financeiro/transacao/editar/{id}:
    put:
      tags:
        - transacoes
      summary: Atualizar uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoInput'
      responses:
        '200':
          description: Transação atualizada

  /api/financeiro/transacao/excluir/{id}:
    delete:
      tags:
        - transacoes
      summary: Remover uma transação
      parameters:
        - name: id
          in: path
          required: true
          description: ID da transação
          schema:
            type: integer
      responses:
        '204':
          description: Transação removida

components:
  schemas:
    Transacao:
      type: object
      properties:
        id:
          type: integer
        tipo:
          type: string
          enum: [receita, despesa]
        categoria:
          type: string
        descricao:
          type: text
        valor:
          type: number
        data:
          type: string
          format: date
    
    TransacaoInput:
      type: object
      properties:
        tipo:
          type: string
          enum: [receita, despesa]
        categoria:
          type: string
        descricao:
          type: string
        valor:
          type: number
        data:
          type: string
          format: date
      required:
        - valor
        - data
        - tipo
        - categoria